<a href="https://colab.research.google.com/github/anjalikokare/MLP-lectures/blob/main/GA3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [92]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.pipeline import FeatureUnion
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.pipeline import FeatureUnion

In [93]:
data = pd.read_csv('Week3_GA_dataset.csv')

In [94]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      748 non-null    object 
 1   V2      748 non-null    object 
 2   V3      748 non-null    float64
 3   V4      748 non-null    float64
 4   V5      748 non-null    object 
 5   Target  748 non-null    object 
dtypes: float64(2), object(4)
memory usage: 35.2+ KB


In [95]:
data.head()

V1    V2       V3    V4        V5 Target
0  2.0  50.0  12500.0  98.0  NEGATIVE    YES
1  0.0  13.0   3250.0  28.0  NEGATIVE    YES
2    ?     ?   4000.0  35.0  NEGATIVE    YES
3    ?  20.0   5000.0  45.0  NEGATIVE    YES
4  1.0  24.0   6000.0  77.0  NEGATIVE     NO

In [96]:
data = data.replace({'?':np.nan})

data['V1'] = data['V1'].astype('float64')
data['V2'] = data['V2'].astype('float64')

In [97]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      743 non-null    float64
 1   V2      743 non-null    float64
 2   V3      748 non-null    float64
 3   V4      748 non-null    float64
 4   V5      748 non-null    object 
 5   Target  748 non-null    object 
dtypes: float64(4), object(2)
memory usage: 35.2+ KB


In [98]:
impute_df = [('Simple Imputer',SimpleImputer(strategy='mean',missing_values=np.nan),[0,1])]

impute_df = ColumnTransformer(impute_df,remainder='passthrough',verbose_feature_names_out=False).set_output(transform='pandas')


scale_df = [('Standard Scaler',StandardScaler(),[0,1,2,3])]

scale_df = ColumnTransformer(scale_df,remainder='drop',verbose_feature_names_out=False).set_output(transform='pandas')

pipe1 = Pipeline(
    [('Imputation',impute_df),
    ('scalling',scale_df)]).set_output(transform='pandas')

pipe1


Pipeline(steps=[('Imputation',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Simple Imputer',
                                                  SimpleImputer(), [0, 1])],
                                   verbose_feature_names_out=False)),
                ('scalling',
                 ColumnTransformer(transformers=[('Standard Scaler',
                                                  StandardScaler(),
                                                  [0, 1, 2, 3])],
                                   verbose_feature_names_out=False))])

In [99]:
encode_df = [('Ordinal Encoder',OrdinalEncoder(),[4])]

encode_df = ColumnTransformer(encode_df,remainder='drop',verbose_feature_names_out=False).set_output(transform=False)

pipe2 = Pipeline([
    ('Encoder',encode_df)
])
pipe2

Pipeline(steps=[('Encoder',
                 ColumnTransformer(transformers=[('Ordinal Encoder',
                                                  OrdinalEncoder(), [4])],
                                   verbose_feature_names_out=False))])

In [100]:
union_pipe = FeatureUnion([
    ('Imputing and Scalling Pipe',pipe1),
    ('Encoding Pipe',pipe2)
]).set_output(transform='pandas')

union_pipe

FeatureUnion(transformer_list=[('Imputing and Scalling Pipe',
                                Pipeline(steps=[('Imputation',
                                                 ColumnTransformer(remainder='passthrough',
                                                                   transformers=[('Simple '
                                                                                  'Imputer',
                                                                                  SimpleImputer(),
                                                                                  [0,
                                                                                   1])],
                                                                   verbose_feature_names_out=False)),
                                                ('scalling',
                                                 ColumnTransformer(transformers=[('Standard '
                                                                                  'Scaler',
                                                                                  StandardScaler(),
                                                                                  [0,
                                                                                   1,
                                                                                   2,
                                                                                   3])],
                                                                   verbose_feature_names_out=False))])),
                               ('Encoding Pipe',
                                Pipeline(steps=[('Encoder',
                                                 ColumnTransformer(transformers=[('Ordinal '
                                                                                  'Encoder',
                                                                                  OrdinalEncoder(),
                                                                                  [4])],
                                                                   verbose_feature_names_out=False))]))])

In [101]:
from sklearn.feature_selection import VarianceThreshold

In [102]:
full_pipe = Pipeline([('Preprocessing',union_pipe),
                     ('VarienceThreshold',VarianceThreshold(threshold=0.1))]).set_output(transform='pandas')

full_pipe

Pipeline(steps=[('Preprocessing',
                 FeatureUnion(transformer_list=[('Imputing and Scalling Pipe',
                                                 Pipeline(steps=[('Imputation',
                                                                  ColumnTransformer(remainder='passthrough',
                                                                                    transformers=[('Simple '
                                                                                                   'Imputer',
                                                                                                   SimpleImputer(),
                                                                                                   [0,
                                                                                                    1])],
                                                                                    verbose_feature_names_out=False)),
                                                                 ('scalling',
                                                                  ColumnTransformer(transformers=[('Standard '
                                                                                                   'Scaler',
                                                                                                   StandardScaler(),
                                                                                                   [0,
                                                                                                    1,
                                                                                                    2,
                                                                                                    3])],
                                                                                    verbose_feature_names_out=False))])),
                                                ('Encoding Pipe',
                                                 Pipeline(steps=[('Encoder',
                                                                  ColumnTransformer(transformers=[('Ordinal '
                                                                                                   'Encoder',
                                                                                                   OrdinalEncoder(),
                                                                                                   [4])],
                                                                                    verbose_feature_names_out=False))]))])),
                ('VarienceThreshold', VarianceThreshold(threshold=0.1))])

In [103]:
X = data.drop('Target',axis=1)
y = data['Target']

In [104]:
full_pipe.fit_transform(X).shape

(748, 4)

In [107]:
X_changed = full_pipe.fit_transform(X)
X_changed.head(2)

Imputing and Scalling Pipe__V1  Imputing and Scalling Pipe__V2  \
0                       -0.938169                        7.709867   
1                       -1.186278                        1.304549   

   Imputing and Scalling Pipe__V3  Imputing and Scalling Pipe__V4  
0                        7.623346                        2.615633  
1                        1.282738                       -0.257881

In [110]:
X['V5'].value_counts()

V5
NEGATIVE    748
Name: count, dtype: int64

In [123]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

In [114]:
new_X = union_pipe.fit_transform(X)
new_X

Imputing and Scalling Pipe__V1  Imputing and Scalling Pipe__V2  \
0                         -0.938169                    7.709867e+00   
1                         -1.186278                    1.304549e+00   
2                          0.000000                   -1.537585e-16   
3                          0.000000                    2.516366e+00   
4                         -1.062223                    3.208833e+00   
..                              ...                             ...   
743                        1.666966                   -5.997340e-01   
744                        1.418858                   -5.997340e-01   
745                        1.666966                   -4.266173e-01   
746                        3.651831                   -7.728506e-01   
747                        7.745616                   -7.728506e-01   

     Imputing and Scalling Pipe__V3  Imputing and Scalling Pipe__V4  \
0                          7.623346                        2.615633   
1                          1.282738                       -0.257881   
2                          1.796842                        0.029471   
3                          2.482313                        0.439973   
4                          3.167784                        1.753579   
..                              ...                             ...   
743                       -0.602307                        0.152621   
744                       -0.602307                        0.727324   
745                       -0.430940                        1.137826   
746                       -0.773675                        0.193671   
747                       -0.773675                        1.548328   

     Encoding Pipe__V5  
0                  0.0  
1                  0.0  
2                  0.0  
3                  0.0  
4                  0.0  
..                 ...  
743                0.0  
744                0.0  
745                0.0  
746                0.0  
747                0.0  

[748 rows x 5 columns]

In [131]:
oe = OrdinalEncoder()
y_encoded = oe.fit_transform(data[['Target']])

rfe = RFE(LogisticRegression(),n_features_to_select = 2)
rfe.fit_transform(new_X,y_encoded.reshape(-1))

array([[-0.93816939,  7.62334626],
       [-1.18627754,  1.28273826],
       [ 0.        ,  1.79684161],
       ...,
       [ 1.66696622, -0.43093957],
       [ 3.65183145, -0.77367514],
       [ 7.74561598, -0.77367514]])

In [132]:
rfe.support_

array([ True, False,  True, False, False])

In [136]:
from sklearn.feature_selection import SequentialFeatureSelector as SFS

sfs = SFS(LogisticRegression(),n_features_to_select = 2,direction='forward')
sfs.fit_transform(new_X,y_encoded.reshape(-1))

array([[ 7.70986653e+00,  2.61563344e+00],
       [ 1.30454949e+00, -2.57880900e-01],
       [-1.53758496e-16,  2.94705348e-02],
       ...,
       [-4.26617275e-01,  1.13782607e+00],
       [-7.72850628e-01,  1.93671355e-01],
       [-7.72850628e-01,  1.54832812e+00]])

In [137]:
sfs.support_

array([False,  True, False,  True, False])

In [138]:
sfs = SFS(LogisticRegression(),n_features_to_select = 2,direction='backward')
sfs.fit_transform(new_X,y_encoded.reshape(-1))

array([[ 7.62334626,  2.61563344],
       [ 1.28273826, -0.2578809 ],
       [ 1.79684161,  0.02947053],
       ...,
       [-0.43093957,  1.13782607],
       [-0.77367514,  0.19367135],
       [-0.77367514,  1.54832812]])

In [139]:
sfs.support_

array([False, False,  True,  True, False])