<a href="https://colab.research.google.com/github/anjalikokare/MLP-lectures/blob/main/week2_mlp2_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numeric Transformers**

* **feature scalling**
* **polynomial transformation**
* **Discretization**

# **Feature Scalling**
* numerical features with difetrent leads to slower convergence of iteratie optimization procedures.
* it is a good practice to scale numerical fatures so that all of them are on same scale

* **StandardScaler**
* **MaxAbsScaler**
* **MinMaxScaler**

# **StandardScaler**

* transform the original features vectors x into new feature vector x' formula

# * **$x' = \frac{x - \mu}{\sigma}$**
* $$
\sigma = \sqrt{\frac{1}{N} \sum_{i=1}^{N} (x_i - \mu)^2}$$


* x = original value
* σ = scale factor (standard deviation ya koi multiplier)
* μ = shift (mean ya offset)
* x' = transformed value


* **Note** : the transformed feature vector x' has mean(${\mu}$)= 0 and standard deviation(${\sigma}$) = 1


In [12]:
import numpy as np
from math import sqrt
from sklearn.preprocessing import StandardScaler

In [14]:
x = np.array((4,3,2,5,6)).reshape(5,1)
u , sigma = 4,sqrt(2)
X_prime = (x-u)/sigma
print(X_prime)

[[ 0.        ]
 [-0.70710678]
 [-1.41421356]
 [ 0.70710678]
 [ 1.41421356]]


In [57]:
x = np.array((0,3,6)).reshape(3,1)

In [58]:
ss = StandardScaler()
ss.fit_transform(x)

array([[-1.22474487],
       [ 0.        ],
       [ 1.22474487]])

# **MaxAbsScaler**
* it transforms the original features vector  into new feature vector so that all values fall within range[-1,1]

* $x' = \frac{x}{maxAbsolutevalue}$
* where MaxAbsoluteValue = max(x.max, | x.min |)

In [16]:
from sklearn.preprocessing import MaxAbsScaler

In [31]:
x = np.array((4,2,5,-2,-100)).reshape(5,1)
print(x)


[[   4]
 [   2]
 [   5]
 [  -2]
 [-100]]


In [32]:
mas = MaxAbsScaler()
mas.fit_transform(x)

array([[ 0.04],
       [ 0.02],
       [ 0.05],
       [-0.02],
       [-1.  ]])

# **MinMaxScaler**

* it transforms the original feature vector x into new feature vector x' so that all values within range[0,1]

* $x' = \frac{x - x.min}{x.max - x.min}$


* x = original value
* x.mean = column ka minimum
* x.max = column ka maximum
* x' = scaled value (0 se 1 ke beech)

In [28]:
from sklearn.preprocessing import MinMaxScaler

In [29]:
x= np.array((15,2,5,-2,-5)).reshape(5,1)
print(x)

[[15]
 [ 2]
 [ 5]
 [-2]
 [-5]]


In [30]:
mms = MinMaxScaler()
mms.fit_transform(x)

array([[1.  ],
       [0.35],
       [0.5 ],
       [0.15],
       [0.  ]])

# **Function Transformer**
* constructs transformed features by applying a user defined function

In [40]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [41]:
x = np.array((128,2,2,256,4,1,512,64)).reshape(4,2)
print(x)

[[128   2]
 [  2 256]
 [  4   1]
 [512  64]]


In [43]:
ft = FunctionTransformer(np.log2)
ft.fit_transform(x)

array([[7., 1.],
       [1., 8.],
       [2., 0.],
       [9., 6.]])

# **Polynomial Transformation**
* generates a new feature matrix consisting of all polynomial combinations of the features with degree less then or equal to the specified degree

In [48]:
from sklearn.preprocessing import PolynomialFeatures

In [49]:
import numpy as np
x = np.array([[2, 3], [4, 5]])

In [50]:
pf = PolynomialFeatures(degree= 2)
pf.fit_transform(x)

array([[ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [51]:
pf = PolynomialFeatures(degree= 3)
pf.fit_transform(x)

array([[  1.,   2.,   3.,   4.,   6.,   9.,   8.,  12.,  18.,  27.],
       [  1.,   4.,   5.,  16.,  20.,  25.,  64.,  80., 100., 125.]])

# **KBinsDisccretizer**
* Divides a continuous variable into bins.
* one hot encoding or ordinal encoding is further applied to the bin labels

In [52]:
from sklearn.preprocessing import KBinsDiscretizer

In [54]:
x = np.array((0,0.125,0.25,0.375,0.5,0.675,0.75,0.875,1.0)).reshape(9,1)
print(x)

[[0.   ]
 [0.125]
 [0.25 ]
 [0.375]
 [0.5  ]
 [0.675]
 [0.75 ]
 [0.875]
 [1.   ]]


In [56]:
kd = KBinsDiscretizer()
kd.fit_transform(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9 stored elements and shape (9, 5)>