<a href="https://colab.research.google.com/github/anjalikokare/MLP-lectures/blob/main/week_2_mlp_2_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Categorical transformers**
* **Feature encoding**
* **label encoding**

# **OneHotEncoder**

*   encodes categorical feature or label as a one-shot numeric array
*   create one-binary-column for each of k unique values
*   exactly one column has 1 in it and rest have 0



In [ ]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [ ]:
x = np.array((1,2,3,1)).reshape(4,1)
print(x)
# isme 3 columns create honge kyuki har ek unique value ka ek hi honga

[[1]
 [2]
 [3]
 [1]]


In [ ]:
obe = OneHotEncoder()
print(obe.fit_transform(x))

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 3)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 0)	1.0


# **LabelEncoder**

* encodes target labels value between 0 to k-1 where k in the number of distinct values

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
y = np.array((1,2,6,1,8,6)).reshape(6,1)
print(y)

[[1]
 [2]
 [6]
 [1]
 [8]
 [6]]


In [ ]:
le = LabelEncoder()  #can trnsform only 1D data
le.fit_transform(y)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 2, 0, 3, 2])

# **OrdinalEncoder**

*Enncodes categorical features with value betweek 0 and k-1 where k in number of distinct values

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
x = np.array((1,2,3,1)).reshape(4,1)
print(x)

[[1]
 [2]
 [3]
 [1]]


In [ ]:
od = OrdinalEncoder()  #can operate multi dimentional data
od.fit_transform(x)

array([[0.],
       [1.],
       [2.],
       [0.]])

# **LabelBinarizer**

* **several regression and binary classification can be extended to multicalss setup one-vs-all fashion**
* **this involves tarining a single regressor classifier per class**
* **convert multiclass labels to binary labels**

In [ ]:
from sklearn.preprocessing import LabelBinarizer

In [ ]:
y = np.array((1,2,6,1,8,6)).reshape(6,1)
print(y)

[[1]
 [2]
 [6]
 [1]
 [8]
 [6]]


In [ ]:
lb = LabelBinarizer()
lb.fit_transform(y)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

# **MultiLabelBinarizer**

* **encodes categorical features with value between 0 and k-1 where k is number of classes**

In [ ]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

In [ ]:
movie_genres = [
    {'action','comedy'},
    {'comedy'},
    {'action','thriller'},
    {'science-fiction','action','thriller'}
]

In [ ]:
df = pd.DataFrame(movie_genres)
df

0         1       2
0           action    comedy    None
1           comedy      None    None
2         thriller    action    None
3  science-fiction  thriller  action

In [ ]:
mlb = MultiLabelBinarizer()
mlb.fit_transform(movie_genres)
# 1 means label is present  0 means label is absent

array([[1, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 1]])

In [ ]:
x = [
    {'heart-dieses','diabetes'},
    {'high-bp'},
    {'heart-dieses','high-bp'},
    {'diabetes'}
]
df = pd.DataFrame(x)
print(df)

          0             1
0  diabetes  heart-dieses
1   high-bp          None
2   high-bp  heart-dieses
3  diabetes          None


In [ ]:
a = MultiLabelBinarizer()
a.fit_transform(x)

array([[1, 1, 0],
       [0, 0, 1],
       [0, 1, 1],
       [1, 0, 0]])

# **add dummy features**

# * ***Augments dataset with a column vector, each value in the column vector is 1***

In [ ]:
from sklearn.preprocessing import add_dummy_feature


In [ ]:
x = np.array((7,1,1,8,2,0,9,6)).reshape(4,2)
print(x)

[[7 1]
 [1 8]
 [2 0]
 [9 6]]


In [ ]:
add_dummy_feature(x)

TypeError: float() argument must be a string or a real number, not 'set'

In [ ]:
from sklearn.preprocessing import add_dummy_feature
add_dummy_feature(x)